name: Deploy React App
run-name: ${{ github.actor }} is testing out GitHub Action  

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: action/checkout@v5

      - name: Set up Node
        uses: action/setup-node@v3
        with: 
          node-version: "20.x"
      
      - name: Install dependencies
        run: npm Install

      - name: Run test
        run: npm run test